[colors.primary]
background = "0x262727"
foreground = "0xe4e4ef"
[cursor]
thickness = 0.5

[font]
size = 14.0
normal = { family = "Hack Nerd Font", style = "Regular" } 

[terminal]
shell = "/usr/bin/zsh" 

[window]
padding = {x=4, y=4}
dynamic_padding = true
decorations = "None"

